=== maxiaolin9495/XML-Praktikum/exercises/exercise3/blackjack.dtd
<!-- DTD created at Wed May 15 22:07:51 CEST 2019 with EditiX XML Editor (http://www.editix.com). Please insert an encoding attribute header for converting any DTD  -->

<!ELEMENT state (deck,card,dealer,player+)>
<!ATTLIST state
  currentPlayer IDREF #REQUIRED>

<!ELEMENT deck (card*)>

<!ELEMENT dealer (card*)>

<!ELEMENT player (hand+)>
<!ATTLIST player
  id ID #REQUIRED
  name CDATA #REQUIRED
  deposit CDATA #REQUIRED>

<!ELEMENT hand (card*)>
<!ATTLIST hand
  box CDATA #REQUIRED>
  
<!ELEMENT card EMPTY>
<!ATTLIST card
  cardColour (Hearts|Diamonds|Clubs|Spades) #REQUIRED
  cardValue (2|3|4|5|6|7|8|9|10|J|Q|K|A) #REQUIRED
  isHidden (true|false) #REQUIRED>

=== maxiaolin9495/XML-Praktikum/exercises/exercise3/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="blackjack.xsl"?>

<!DOCTYPE state SYSTEM "blackjack.dtd">

<state currentPlayer="PER-1">
    <deck>
        <card cardColour="Clubs" cardValue="2" isHidden="true"/>
        <card cardColour="Clubs" cardValue="3" isHidden="true"/>
    </deck>
    <card cardColour="Spades" cardValue="Q" isHidden="true"/>
    <dealer>
        <card cardColour="Clubs" cardValue="A" isHidden="true"/>
        <card cardColour="Spades" cardValue="A" isHidden="false"/>
    </dealer>
    <player id="PER-1" name="Player 1" deposit="200">
        <hand box="20">
            <card cardColour="Spades" cardValue="J" isHidden="false"/>
            <card cardColour="Spades" cardValue="10" isHidden="false"/>
            <card cardColour="Spades" cardValue="7" isHidden="false"/>
        </hand>
        <hand box="10">
            <card cardColour="Spades" cardValue="J" isHidden="false"/>
            <card cardColour="Spades" cardValue="Q" isHidden="false"/>
        </hand>
    </player>
    <player id="PER-2" name="Player 2" deposit="200">
        <hand box="15">
            <card cardColour="Diamonds" cardValue="7" isHidden="false"/>
            <card cardColour="Diamonds" cardValue="8" isHidden="false"/>
        </hand>
    </player>
</state>
